name: Generate Snake Animation
on:
  schedule: # runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.MY_TOKEN }} # Use your custom token name

      # New step to list the contents of the directory
      - name: List directory contents
        run: ls -R

      - name: Check for svg file
        run: |
          if [ -f github-snake.svg ]; then
            echo "File github-snake.svg exists."
          else
            echo "File github-snake.svg does NOT exist."
          fi

      - name: Commit and push the result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-snake.svg || echo "File github-snake.svg not found, nothing to add"
          git commit -m "Generated snake animation" || echo "No changes to commit"
          git push || echo "Nothing to push"
