name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate snake animation
      - name: Generate Snake Animation
        id: generate-snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: 'schrodingerspet'  # Ensure this is your correct GitHub username

      # Step 3: Upload the generated animation as artifacts
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: |
            github-snake.svg
            github-snake.gif
