name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        id: generate-snake
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: 'schrodingerspet'
          svg_out_path: 'github-snake.svg'
          gif_out_path: 'github-snake.gif'
          # Remove github_token as it is no longer required.
          
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: |
            github-snake.svg
            github-snake.gif

