name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Generate snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: schrodingerspet
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Push the generated files to the repository
      - name: Push to GitHub repository
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generate Snake Animation'
          add: 'dist'
