name: Generate Snake Animation
on:
  schedule: # runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: schrodingerspet
      - name: Commit and push the result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-snake.svg
          git commit -m "Generated snake animation"
          git push
